config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'

  resources :lists, only: [ :index, :show, :new, :create ] do
    resources :bookmarks, only: [ :new, :create ]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  has_one_attached :photo
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_one_attached :photo
  # belongs_to :list
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    @bookmark.list = @list
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to @list
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :photo)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for(bookmark) do |f| %>
  <!-- [...] -->
  <%= f.input :photo, as: :file %>
  <!-- [...] -->
<% end %>

app/views/bookmarks/new.html.erb
<h2>New Bookmark</h2>

<%= simple_form_for [ @list, @bookmark ], method: :post, url: list_bookmarks_path(params[:list_id]) do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, as: :select %>
  <%= f.submit "Submit bookmark", class: "btn btn-primary" %>
<% end %>

<%= link_to "Back to list", list_path(params[:list_id]) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <!-- [...] -->
  <%= f.input :photo, as: :file %>
  <!-- [...] -->
<% end %>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://thumbs.dreamstime.com/b/top-view-film-bobbin-airy-delicious-popcorn-banner-cinema-concept-top-view-film-bobbin-airy-delicious-popcorn-banner-210961621.jpg)" >
  <div class="container">
    <h1>Save any kind of movies</h1>
    <p>Classic</p>
  </div>
</div>

<div class="container">

  <div class="button-corner">
    <h2>My Lists</h2>
    <%= link_to "Add a new list", new_list_path, class: "btn btn-flat" %>
  </div>
  
  <div class="cards">
    <% @lists.each do |list| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key %>')">
        <%= link_to list.name, list_path(list) %>
      </div>
    <% end %>
  </div>

</div>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>



<%= link_to "Back to list", lists_path %>

app/views/lists/show.html.erb
<div class="container">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key %>')">
    <%= @list.name %>
    <div class="card-bookmark-count">
      <%= @bookmarks.count %> movies
    </div>
  </div>

<div class="button-corner">
  <h2>Bookmarks list</h2>
  <div>
    <%= link_to "Add a bookmark",  new_list_bookmark_path(@list), class: "btn btn-gradient"%>
    <%= link_to "Back to list", lists_path, class: "btn btn-gradient" %>
  </div>
</div>

<article>
<ul class="list-group">
  <% @bookmarks.each do |bookmark| %>
    <li class="list-group-item"><%= bookmark.movie.title %>
    <%= link_to "Remove",
                  bookmark_path(bookmark), # this links to the route path where delete is
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>
</article>

</div>